version: "3"
 
services:
  jenkins:
    user: root
    image: "jenkinsci/blueocean"
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge